- name: "Screen 1"
  urls:
    - "http://google.com"
    - "http://github.com"
  layout:
    name: "carrousel"
    time: 5000

- name: "Screen 2"
  urls:
    - "http://lanacion.com.ar"
    - "http://stackoverflow.com"
  layout:
    name: "carrousel"
    time: 5000

- name: "Screen 3"
  urls:
    - "http://twitter.com"
    - "http://start"
  layout:
    name: "carrousel"
    time: 5000
